export const referencesTemplate = {
  articles: {
    lists: [],
    type: 'articles',
    label: 'Journal Article',
    description: 'A scholarly article published in an academic journal.',
    template: {
      id: null,
      tags: [''],
      type: '',
      title: '',
      authors: [
        {
          firstname: '',
          lastname: '',
        },
      ],
      subtitle: '',
      journal: '',
      publisher: '',
      date: '',
      DOI: '',
      volume: '',
      issue: '',
      page: '',
      URL: '',
      language: '',
    },
  },
  books: {
    lists: [],
    type: 'books',
    label: 'Book',
    description: 'A complete book written by one or more authors.',
    template: {
      id: null,
      tags: [''],
      title: '',
      subtitle: '',
      authors: [
        {
          firstname: '',
          lastname: '',
        },
      ],
      publisher: '',
      date: '',
      page: '',
      URL: '',
    },
  },
  bookChapter: {
    lists: [],
    type: 'bookChapter',
    label: 'Book Chapter',
    description: 'A chapter or section within an edited book.',
    template: {
      id: null,
      tags: [''],
      title: '',
      subtitle: '',
      authors: [
        {
          firstname: '',
          lastname: '',
        },
      ],
      ['main-title']: '',
      ['main-authors']: [
        {
          firstname: '',
          lastname: '',
        },
      ],
      publisher: '',
      date: '',
      pages: '',
      URL: '',
    },
  },
  conferencePaper: {
    lists: [],
    type: 'conferencePaper',
    label: 'Conference Paper',
    description: 'A paper presented at a conference or symposium.',
    template: {
      id: null,
      tags: [''],
      title: '',
      authors: [
        {
          firstname: '',
          lastname: '',
        },
      ],
      name: '',
      location: '',
      publisher: '',
      date: '',
      page: '',
      URL: '',
    },
  },
  dissertation: {
    lists: [],
    type: 'dissertation',
    label: 'Dissertation or Thesis',
    description: 'An academic dissertation or dissertation submitted for a degree.',
    template: {
      id: null,
      tags: [''],
      title: '',
      authors: [
        {
          firstname: '',
          lastname: '',
        },
      ],
      institution: '',
      degree: '',
      date: '',
      URL: '',
    },
  },
  report: {
    lists: [],
    type: 'report',
    label: 'Report',
    description: 'A technical or research report published by an institution or organization.',
    template: {
      id: null,
      tags: [''],
      type: '',
      title: '',
      authors: [
        {
          firstname: '',
          lastname: '',
        },
      ],
      journal: '',
      publisher: '',
      date: '',
      DOI: '',
      URL: '',
      language: '',
    },
  },
  web: {
    lists: [],
    type: 'web',
    label: 'Web Page',
    description: 'Content from an online source, such as a website or blog post.',
    template: {
      id: null,
      tags: [''],
      title: '',
      authors: [
        {
          firstname: '',
          lastname: '',
        },
      ],
      name: '',
      date: '',
      URL: '',
      accessDate: '',
    },
  },
  newspaperArticle: {
    lists: [],
    type: 'newspaperArticle',
    label: 'Newspaper Article',
    description: 'An article published in a newspaper.',
    template: {
      id: null,
      tags: [''],
      title: '',
      authors: [
        {
          firstname: '',
          lastname: '',
        },
      ],
      name: '',
      date: '',
      URL: '',
    },
  },
  magazineArticle: {
    lists: [],
    type: 'magazineArticle',
    label: 'Magazine Article',
    description: 'An article published in a magazine or popular journal.',
    template: {
      id: null,
      tags: [''],
      title: '',
      authors: [
        {
          firstname: '',
          lastname: '',
        },
      ],
      name: '',
      issue: '',
      date: '',
      URL: '',
    },
  },
  software: {
    lists: [],
    type: 'software',
    label: 'Software',
    description: 'Software or code used or cited in the research.',
    template: {
      id: null,
      tags: [''],
      title: '',
      authors: [
        {
          firstname: '',
          lastname: '',
        },
      ],
      version: '',
      publisher: '',
      date: '',
      URL: '',
    },
  },

  legislation: {
    lists: [],
    type: 'legislation',
    label: 'Legislation',
    description: 'A law, statute, or regulation.',
    template: {
      id: null,
      tags: [''],
      title: '',
      authors: [
        {
          firstname: '',
          lastname: '',
        },
      ],
      institution: '',
      degree: '',
      date: '',
    },
  },

  manuscript: {
    lists: [],
    type: 'manuscript',
    label: 'Manuscript',
    description: 'An unpublished or in-progress work.',
    template: {
      id: null,
      tags: [''],
      title: '',
      authors: [
        {
          firstname: '',
          lastname: '',
        },
      ],
      status: '',
      submissionDate: '',
      URL: '',
    },
  },
  presentation: {
    lists: [],
    type: 'presentation',
    label: 'Presentation or Lecture',
    description: 'An oral presentation, lecture, or slide deck.',
    template: {
      id: null,
      tags: [''],
      title: '',
      authors: [
        {
          firstname: '',
          lastname: '',
        },
      ],
      event: '',
      location: '',
      date: '',
      URL: '',
    },
  },
};
