export const referencesTemplate = {
  articles: {
    lists: [],
    type: 'articles',
    label: 'Journal Article',
    description: 'A scholarly article published in an academic journal.',
  },
  books: {
    lists: [],
    type: 'books',
    label: 'Book',
    description: 'A complete book written by one or more authors.',
  },
  bookChapter: {
    lists: [],
    type: 'bookChapter',
    label: 'Book Chapter',
    description: 'A chapter or section within an edited book.',
  },
  conferencePaper: {
    lists: [],
    type: 'conferencePaper',
    label: 'Conference Paper',
    description: 'A paper presented at a conference or symposium.',
  },
  thesis: {
    lists: [],
    type: 'thesis',
    label: 'Thesis or Dissertation',
    description: 'An academic dissertation or thesis submitted for a degree.',
  },
  report: {
    lists: [],
    type: 'report',
    label: 'Report',
    description: 'A technical or research report published by an institution or organization.',
  },
  web: {
    lists: [],
    type: 'web',
    label: 'Web Page',
    description: 'Content from an online source, such as a website or blog post.',
  },
  newspaperArticle: {
    lists: [],
    type: 'newspaperArticle',
    label: 'Newspaper Article',
    description: 'An article published in a newspaper.',
  },
  magazineArticle: {
    lists: [],
    type: 'magazineArticle',
    label: 'Magazine Article',
    description: 'An article published in a magazine or popular journal.',
  },
  dataset: {
    lists: [],
    type: 'dataset',
    label: 'Dataset',
    description: 'A published or archived dataset used in research.',
  },
  software: {
    lists: [],
    type: 'software',
    label: 'Software',
    description: 'Software or code used or cited in the research.',
  },
  interview: {
    lists: [],
    type: 'interview',
    label: 'Interview',
    description: 'A personal or published interview used as a source.',
  },
  film: {
    lists: [],
    type: 'film',
    label: 'Film or Video',
    description: 'A film, video, or documentary referenced in the research.',
  },
  legalCase: {
    lists: [],
    type: 'legalCase',
    label: 'Legal Case',
    description: 'A legal decision or court case.',
  },
  legislation: {
    lists: [],
    type: 'legislation',
    label: 'Legislation',
    description: 'A law, statute, or regulation.',
  },
  patent: {
    lists: [],
    type: 'patent',
    label: 'Patent',
    description: 'A government-issued patent document.',
  },
  manuscript: {
    lists: [],
    type: 'manuscript',
    label: 'Manuscript',
    description: 'An unpublished or in-progress work.',
  },
  presentation: {
    lists: [],
    type: 'presentation',
    label: 'Presentation or Lecture',
    description: 'An oral presentation, lecture, or slide deck.',
  },
  audio: {
    lists: [],
    type: 'audio',
    label: 'Audio Recording',
    description: 'A recorded audio source, such as a podcast.',
  },
  image: {
    lists: [],
    type: 'image',
    label: 'Image or Figure',
    description: 'A visual source such as a photo, painting, or diagram.',
  },
};
