export const referencesTemplate = {
  articles: {
    lists: [],
    type: 'articles',
    label: 'Journal Article',
    description: 'A scholarly article published in an academic journal.',
    template: {
      id: null,
      title: '',
      authors: [''],
      type: '',
      subtitle: '',
      journal: '',
      publisher: '',
      ['published-date']: '',
      DOI: '',
      language: '',
      volume: '',
      issue: '',
      page: '',
      URL: '',
    },
  },
  books: {
    lists: [],
    type: 'books',
    label: 'Book',
    description: 'A complete book written by one or more authors.',
    template: {
      id: null,
      title: '',
      subtitle: '',
      authors: [''],
      publisher: '',
      ['published-date']: '',
      pages: '',
      infoLink: '',
    },
  },
  bookChapter: {
    lists: [],
    type: 'bookChapter',
    label: 'Book Chapter',
    description: 'A chapter or section within an edited book.',
    template: {
      id: null,
      title: '',
      subtitle: '',
      authors: [''],
      ['chapter-title']: '',
      ['chapter-authors']: [''],
      publisher: '',
      ['published-date']: '',
      pages: '',
      infoLink: '',
    },
  },
  conferencePaper: {
    lists: [],
    type: 'conferencePaper',
    label: 'Conference Paper',
    description: 'A paper presented at a conference or symposium.',
    template: {
      id: null,
      title: '',
      authors: [''],
      conferenceName: '',
      location: '',
      ['published-date']: '',
      page: '',
      URL: '',
    },
  },
  thesis: {
    lists: [],
    type: 'thesis',
    label: 'Thesis or Dissertation',
    description: 'An academic dissertation or thesis submitted for a degree.',
    template: {
      id: null,
      title: '',
      authors: [''],
      institution: '',
      degree: '',
      ['published-date']: '',
      URL: '',
    },
  },
  report: {
    lists: [],
    type: 'report',
    label: 'Report',
    description: 'A technical or research report published by an institution or organization.',
    template: {
      id: null,
      title: '',
      authors: [''],
      institution: '',
      reportNumber: '',
      ['published-date']: '',
      URL: '',
    },
  },
  web: {
    lists: [],
    type: 'web',
    label: 'Web Page',
    description: 'Content from an online source, such as a website or blog post.',
    template: {
      id: null,
      title: '',
      authors: [''],
      websiteName: '',
      ['published-date']: '',
      URL: '',
      accessDate: '',
    },
  },
  newspaperArticle: {
    lists: [],
    type: 'newspaperArticle',
    label: 'Newspaper Article',
    description: 'An article published in a newspaper.',
    template: {
      id: null,
      title: '',
      authors: [''],
      newspaperName: '',
      page: '',
      ['published-date']: '',
      URL: '',
    },
  },
  magazineArticle: {
    lists: [],
    type: 'magazineArticle',
    label: 'Magazine Article',
    description: 'An article published in a magazine or popular journal.',
    template: {
      id: null,
      title: '',
      authors: [''],
      magazineName: '',
      issue: '',
      ['published-date']: '',
      URL: '',
    },
  },
  dataset: {
    lists: [],
    type: 'dataset',
    label: 'Dataset',
    description: 'A published or archived dataset used in research.',
    template: {
      id: null,
      title: '',
      authors: [''],
      repository: '',
      DOI: '',
      ['published-date']: '',
      URL: '',
    },
  },
  software: {
    lists: [],
    type: 'software',
    label: 'Software',
    description: 'Software or code used or cited in the research.',
    template: {
      id: null,
      title: '',
      authors: [''],
      version: '',
      publisher: '',
      ['published-date']: '',
      URL: '',
    },
  },
  interview: {
    lists: [],
    type: 'interview',
    label: 'Interview',
    description: 'A personal or published interview used as a source.',
    template: {
      id: null,
      title: '',
      interviewee: [''],
      interviewer: [''],
      date: '',
      location: '',
      URL: '',
    },
  },
  film: {
    lists: [],
    type: 'film',
    label: 'Film or Video',
    description: 'A film, video, or documentary referenced in the research.',
    template: {
      id: null,
      title: '',
      authors: [''],
      institution: '',
      degree: '',
      ['published-date']: '',
    },
  },
  legalCase: {
    lists: [],
    type: 'legalCase',
    label: 'Legal Case',
    description: 'A legal decision or court case.',
    template: {
      id: null,
      title: '',
      authors: [''],
      institution: '',
      degree: '',
      ['published-date']: '',
    },
  },
  legislation: {
    lists: [],
    type: 'legislation',
    label: 'Legislation',
    description: 'A law, statute, or regulation.',
    template: {
      id: null,
      title: '',
      authors: [''],
      institution: '',
      degree: '',
      ['published-date']: '',
    },
  },
  patent: {
    lists: [],
    type: 'patent',
    label: 'Patent',
    description: 'A government-issued patent document.',
    template: {
      id: null,
      title: '',
      authors: [''],
      institution: '',
      degree: '',
      ['published-date']: '',
    },
  },
  manuscript: {
    lists: [],
    type: 'manuscript',
    label: 'Manuscript',
    description: 'An unpublished or in-progress work.',
    template: {
      id: null,
      title: '',
      authors: [''],
      status: '',
      submissionDate: '',
      URL: '',
    },
  },
  presentation: {
    lists: [],
    type: 'presentation',
    label: 'Presentation or Lecture',
    description: 'An oral presentation, lecture, or slide deck.',
    template: {
      id: null,
      title: '',
      presenter: [''],
      event: '',
      location: '',
      date: '',
      URL: '',
    },
  },
  audio: {
    lists: [],
    type: 'audio',
    label: 'Audio Recording',
    description: 'A recorded audio source, such as a podcast.',
    template: {
      id: null,
      title: '',
      authors: [''],
      institution: '',
      degree: '',
      ['published-date']: '',
    },
  },
  image: {
    lists: [],
    type: 'image',
    label: 'Image or Figure',
    description: 'A visual source such as a photo, painting, or diagram.',
    template: {
      id: null,
      title: '',
      authors: [''],
      institution: '',
      degree: '',
      ['published-date']: '',
    },
  },
};
